### ISSUE TITLE
importing data from Lastpass

### ISSUE THREAD

**Issue by getreadyforme** [bitwarden/help#10]
I had a few issues with the help instructions about export/import outlined here: https://help.bitwarden.com/getting-started/import-from-lastpass/. 

I'm using Lastpass 3.3.4 on Firefox 52.

Issue 1.  
Step 1 of "Export Your Passwords From The LastPass Browser Extension" says to navigate to “More Options” > “Advanced” > “Export” > “LastPass CSV File”.  That path only applies on the LP web vault, not the browser extension.  Here is the correct path for the browser extension:

![lp2017-04-11_004251](https://cloud.githubusercontent.com/assets/7669787/24898281/355143a6-1e51-11e7-94c1-8dac966dff67.png)

Issue 2. 
When I follow the instructions under "Export Your Passwords From The LastPass Browser Extension", and then import, I get:
![bw_error2](https://cloud.githubusercontent.com/assets/7669787/24899069/de248be4-1e53-11e7-82c5-21c0d38ffa48.png)

Issue 3. 
When I followed the instructions under "Export Your Passwords From The LastPass.com Web Vault", and then import, I get: 
![bw_error1](https://cloud.githubusercontent.com/assets/7669787/24899005/a8cc3906-1e53-11e7-882c-755805f3f7c0.png)
I noticed that the data is pasted in a single column of the CSV file.  

The problem is in steps 5 and 6 which state:
5. Create a new text file on your desktop called “lastpass_export.csv”.
6. Edit this file, paste your CSV data that was copied from step 4. Save.

The only way this works is if I do the following:
- create a text file
- paste the LP data from the web vault into the text file and save it (.txt extension) 
- change the file extension from txt to csv.  
Only then the import works, and the CSV data is in multiple columns.  It looks similar to the formatting of how the browser extension exports the file, but it can't be the same because that method didn't work at all.  

I'm guessing these issues are the reason some users gave thumbs down on the help page because maybe they could not import their data.

**Comment by kspearrin** [comment]
The instructions are different because it appears you are using an older version of the LastPass browser extension. The instructions are more for the LastPass 4. Also, you should use the web vault to export your logins due to issues like this with the browser extension.

Whenever you create the csv file, you should open it in a text editor, not a spreadsheet program to avoid the problem of pasting it in a single column. that you mentioned. We should probably update the instructions to include this.

**Comment by getreadyforme** [comment]
> The instructions are different because it appears you are using an older version of the LastPass browser extension. The instructions are more for the LastPass 4.

Well, you say it's an older version, and technically that's true, but that's actually the **latest** version posted on the Mozilla addon site  https://addons.mozilla.org/en-US/firefox/addon/lastpass-password-manager/?src=search, which is where most users get their extensions.   So at the very least it may help to mention these things.

> Whenever you create the csv file, you should open it in a text editor, not a spreadsheet program to avoid the problem of pasting it in a single column. that you mentioned. We should probably update the instructions to include this.

Exactly!  Most people probably don't know these things, they just double click on the CSV file and 90% of the time it will open in MS Excel or other default program.

**Comment by kspearrin** [comment]
We have updated the instructions to include copy/pasting the data instead of making a new file. Also, we have removed the instructions for the browser extension and only recommend the web vault to export.
