### ISSUE TITLE
Guide for Firefox ignores Firefox's new password export feature

### ISSUE THREAD

**Issue by 12people** [bitwarden/help#163]
The ["Import your data from Firefox" page](https://bitwarden.com/help/article/import-from-firefox/) states "Since version 57, the Firefox browser no longer provides any password export addons and you will need to use third-party tools." This is no longer true, however — [Firefox 59 adds back password export](https://support.mozilla.org/en-US/kb/export-login-data-firefox-lockwise) functionality.

Unfortunately, as it stands, the current online version of Bitwarden doesn't import those exported passwords correctly (see [issue 831](https://github.com/bitwarden/server/issues/831)). However, once the new version is up, it'd be good to revise the article entirely and recommend using the official export tool.

For now, it'd be good to mention that while Firefox now supports password exports, there is a bug preventing them to be imported correctly and the open-source password export extension should be used instead.

**Comment by LiberalArtist** [comment]
It looks like https://github.com/bitwarden/server/issues/831 was fixed in https://github.com/bitwarden/jslib/pull/132, which has been merged, and it seemed to be working when I just tried it.

**Comment by tgreer-bw** [comment]
Fixed in the above PR. 👍
