### ISSUE TITLE
Some of the links in  help/_articles/faqs/security-faqs.md are broken.

### ISSUE THREAD

**Issue by vachan-maker** [bitwarden/help#184]
@tgreer-bw  
You may be aware of this issue but some of the links in the Security FAQ under **Table of Contents** are broken  
Links which are broken

- Master Password Stored Locally?
- Third party scripts, libraries, and services
- Security General (Whitepaper, Audit report, etc.)
- Self-signed Certificate Setup, On-premises/self-hosted
- Web Browser Extension Security/Safety Concern
- Duo MFA / 2FA / Two-step Login Requirement

Thanks

**Comment by tgreer-bw** [comment]
Yep! There are extra '-' spaces for some reason, due to the formatting of the titles. I'll be addressing them in all of the FAQ docs (aside from Feature FAQs, which has already been fixed).

**Comment by vachan-maker** [comment]
Great.
I am just curious, does the help documentation automatically get updated when you merge pull requests?If it is, is kinda cool.

**Comment by tgreer-bw** [comment]
It does actually! GitHub pages rebuilds and deploys using GitHub Actions.

Makes it very easy 😄
