### ISSUE TITLE
Include Group Syntax not working as expected #POST2

### ISSUE THREAD

**Issue by mrventerj** [bitwarden/help#220]
Already posted in /
directory-connector

Getting no response.

Hi

I did do the first method "Include:Group A " but then I have to specify each users under users before they get an invite.

So the second method is (from my understanding) invite all users in the group by using the syntax 'includeGroup:xxxx-xxxx-xxx"

I clicked test - but I was expecting only my test group to appear and the one test user, but the test that run listed all the groups I have in Azure AD.

Is this normal behavior?

Kind Regards,

**Comment by fschillingeriv** [comment]
Looks like the team was able to provide some a solution [here](https://github.com/bitwarden/directory-connector/issues/68). Closing this Issue accordingly.
