### ISSUE TITLE
Crypto Disclosure - Interactive "whitepaper"

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/help#26]
Build an interactive "whitepaper" app that walks though how bitwarden implements crypto.

WIP: https://help.bitwarden.com/crypto.html

**Comment by code-noggin** [comment]
While https://help.bitwarden.com/crypto.html demonstrates keys being generated, it does not explain what and how encryption is used in bitwarden. 

Can we get a written "whitepaper" as requested in issue bitwarden/core#183 ?

**Comment by kspearrin** [comment]
This is still a WIP and will contain more than just code when complete.
