### ISSUE TITLE
Specified instructions doesn't work in Chrome 63.0.3239.108

### ISSUE THREAD

**Issue by pzmarzly** [bitwarden/help#28]
After doing everything specified in [the guide](https://help.bitwarden.com/article/import-from-chrome/) I end up with file `chrome_passwords.csv` with following contents:
```
name,url,username,password
```
Just 1 line. Bitwarden returns error about invalid data provided.

The working way to export my passwords was:
1. Close Chrome
2. Run it with `google-chrome-stable --password-store=basic`
3. Wait for it to sync (check whether `chrome://settings/passwords` contains passwords)
4. Close Chrome
5. Run `sqlite3 -header -csv -separator "," ~/.config/google-chrome/Default/Login\ Data "SELECT signon_realm AS name,signon_realm AS url,username_value AS username,password_value AS password FROM logins" > ~/Passwords.csv`
6. Remove `~/.config/google-chrome/Default/Login Data` for security and to un-glitch Chrome sync

OS: Linux Manjaro
Chrome version: Version 63.0.3239.108 (Official Build) (64-bit)

**Comment by kspearrin** [comment]
This looks to be an issue in the current version of Chrome. See https://productforums.google.com/forum/#!topic/chrome/Ayaw6XYhahM;context-place=forum/chrome
