### ISSUE TITLE
Add information for on-premise Yubico OTP Validation Server

### ISSUE THREAD

**Issue by ggrzeczkowicz** [bitwarden/help#311]
It is possible to use custom URL for the Yubico OTP Validation Server, but this option is not documented.

**Comment by fschillingeriv** [comment]
@ggrzeczkowicz thanks for the contribution! Your issue & PR tipped us off to the fact all our environment variables needed better documenting, so I put together this article to solve that: https://bitwarden.com/help/article/environment-variables/

If you know of any variable not captured, I encourage you to add them
