### ISSUE TITLE
[Azure AD Sync] Explain or reduce required application API permissions

### ISSUE THREAD

**Issue by Nothing4You** [bitwarden/help#32]
Hey there,

does bitwarden actually require all these permissions in the image on step 1? I wouldn't expect it to require access to managing applications or devices for example.

https://help.bitwarden.com/article/azure-active-directory/#grant-application-permissions

**Comment by kspearrin** [comment]
No, we should probably adjust that.

Try just selecting:

**App Permissions**

- Read directory data
- Read all hidden memberships

**Delegated Permissions**

- Read Directory data
- Read all groups
- Read all user's full profile
- Read all users' basic profiles
- Read hidden memberships

**Comment by kspearrin** [comment]
I have removed the step from the docs altogether. The **Windows Azure Active Directory** API permission set is not even needed. It can be deleted. You only need **Microsoft Graph** API permissions with:

   - Application Permissions:
     - "Read all users' full profiles"
     - "Read all groups"
   - Delegated Permissions:
     - "Read all groups"
     - "Read all users' full profiles"
     - "Read all users basic profiles"

**Comment by jamieboy05** [comment]
Just an update on this, I wanted to report that these permissions no longer work.  The permissions need to include the ones that @kspearrin posted above on May 7th plus Directory.Read.All - Read directory data on both App Permissions and Delegated Permissions.  The sync will fail with error “Insufficient privileges to complete the operation”.
