### ISSUE TITLE
How does the change email and change password functionality work?

### ISSUE THREAD

**Issue by awwong1** [bitwarden/help#34]
I'm curious as to how the `changeMasterPassword` and `changeEmail` functionality works, given that BitWarden shouldn't ever be able to view user encrypted data.

How are the existing items stored in the database updated such that a user can decrypt them using the new master password or email? (In StandardFile/StandardNotes, the client fetches all of the encrypted items, decrypts/re-encrypts them, then sends them all back to the server.)

**Comment by kspearrin** [comment]
Every user has an encryption key that never changes. This key encrypts all of your data. Your master password encrypts the key. When you change your master password this single key is reencrypted.

**Comment by awwong1** [comment]
Okay, that makes sense. Thanks!

**Comment by awwong1** [comment]
Sorry, I was thinking about this some more.
If an attacker ever compromised your email/password, they could decrypt the your encryption key. Changing your email or password at this point would be futile.

Is there any functionality to detect or re-encrypt all existing items stored within the bitwarden core?

**Comment by kspearrin** [comment]
If a user ever compromised your username and password, yes of course they can decrypt everything. Changing your password would block access again to that user since they would not be able to access your encrypted data again.

There is no key rotation functions available at the moment, but it's something we've considered.

**Comment by awwong1** [comment]
Okay, thanks again Kyle!
