### ISSUE TITLE
Better example URI than https://google.com

### ISSUE THREAD

**Issue by ypid** [bitwarden/help#394]
I don’t find the Google URIs that are in the examples all over the place appropriate for a Password Manager that has Privacy as one of it’s selling points. It might scare people away.

As I needed a good example domain, that is also commonly known and uses multiple subdomains (for #158), I propose to switch all examples to https://en.wikipedia.org/

**Comment by Greenderella** [comment]
Hi @ypid,

Thank you so much for your contribution it has already been merged: https://github.com/bitwarden/help/pull/158

**Comment by ypid** [comment]
This was a broader issue. I only fixed on occurrence. There are still man cases remaining: https://github.com/bitwarden/help/search?q=google.com Can you reopen?
