### ISSUE TITLE
Error while importing from Lastpass: "This organization can only have a maximum of 2 collections"

### ISSUE THREAD

**Issue by tgreer-bw** [bitwarden/help#408]
@kunalgrover05 commented on [Fri Feb 19 2021](https://github.com/bitwarden/server/issues/1152)

I was trying to migrate my data from LastPass -> Bitwarden Free tier, and I got an error: "This organization can only have a maximum of 2 collections". 

I found the issue to be very non-descriptive about what is going on, and couldn't find anything on searching about it. The reason for that was LastPass exports the content including a "grouping" field which they determine as the most reasonable bucket for the website, eg: Email / Education etc. This leads to multiple organizations being created which causes the error and stops an import. 

Workaround: Simply delete the grouping column and the data will get imported. 

Ask: It should be clear what the error means and a workaround should be present in the onboarding help section: https://bitwarden.com/help/article/import-from-lastpass/

---

@tgreer-bw commented on [Fri Feb 19 2021](https://github.com/bitwarden/server/issues/1152#issuecomment-782182526)

@fschillingeriv - this and the field text limits would be good to add I think.

**Comment by fschillingeriv** [comment]
resolved by #410!

**Comment by drpeppercan** [comment]
It's nice to see that this issue it's been worked on. 
But I guess it has not been resolved yet, as I just had it now :( 

I guess I'll try deleting the Grouping column.

DPC
