### ISSUE TITLE
Social security number fields should be hidden by default

### ISSUE THREAD

**Issue by kylemart** [bitwarden/help#417]
When viewing an identity, I should not be immediately shown the value of the social security number field. Like any other secret field (e.g. the security code within a credit card entry), it should be hidden — unless explicitly made visible — behind dots.

**Comment by vachan-maker** [comment]
The Bitwarden Help repository is the documentation of Bitwarden.
I would suggest you to close this and create a topic on https://community.bitwarden.com. You can get support and request features here.
For filing bug report, please do so in the respective repo.
I will see you there.
Thanks
