### ISSUE TITLE
Wrong screenshot

### ISSUE THREAD

**Issue by Normrubin-TO** [bitwarden/help#422]
Suggestion or Edit for: bitwarden.com/help/article/import-from-lastpass/ 

The first screenshot is fine, but the second one shows the export from BITWARDEN instead of LASTPASS!

**Comment by KawinZheng** [comment]
It seems that you are confused by the bitwarden website on the background, however, the dropdown menu shown is indeed from LastPass

**Comment by Normrubin-TO** [comment]
And why exactly is it helpful to anybody to show the bitwarden website on the background when the task is to export data from LastPass?
