### ISSUE TITLE
Add a static example image for custom fields Name and Value

### ISSUE THREAD

**Issue by MagicFirefly** [bitwarden/help#423]
Suggestion or Edit for: bitwarden.com/help/article/custom-fields/

4. Paste the copied element id in the Name field.
5. Specify the desired information to be auto-filled (in the above example, a PIN) in the Value field.

![image](https://user-images.githubusercontent.com/77048997/108927699-c617cb80-760e-11eb-8384-b801cfe9769c.png)

6. Save the Vault item.

**Comment by fschillingeriv** [comment]
resolved by #431
