### ISSUE TITLE
A suggestion for the Password protection mechanism

### ISSUE THREAD

**Issue by philwang90** [bitwarden/help#425]
Hi, there is a suggestion for the protection mechanism. Now we need to use Bitwarden after input the main pwd successfully, then we can check the pwd library or autofill a username and pwd.  But i think this is not easy to use.
I suggest Bitwarden can change the mechanism:
1. user can use autofill all the time, no need to unlock Bitwarden, but user cannot see the pwd library.
2. user will see the pwd library after input their main pwd.

Suggestion or Edit for: bitwarden.com/help/

**Comment by fschillingeriv** [comment]
Hey @philwang90, like our friend @vachan-maker mentioned, Feature Requests are best exposed to the team [here](https://community.bitwarden.com/t/about-the-feature-requests-category/12).

Meantime, closing this issue.
