### ISSUE TITLE
Feature Requests: Browser Extension Timeout On Idle and Password Sharing

### ISSUE THREAD

**Issue by DRVM** [bitwarden/help#426]
I would like to switch to Bitwarden from LastPass but am hung up on 2 issues:
1. The browser extension timeout is dangerous. Without an "on idle" option I could be constantly having to login due to a short timeout or walk away from my computer and anyone else could access because of a long timeout.
2. There are times I need to share my password with others in a secure fashion and LastPass offers this option.

Thank you!

**Comment by vachan-maker** [comment]
The Bitwarden Help repository is the documentation of Bitwarden.
I would suggest you to close this and create a topic on https://community.bitwarden.com. You can get support and request features here.
For filing bug report, please do so in the respective repo.
I will see you there.
Thanks
