### ISSUE TITLE
Article needs update

### ISSUE THREAD

**Issue by as232** [bitwarden/help#427]
Suggestion or Edit for: bitwarden.com/help/article/forgot-master-password/

The link mentioned "https://vault.bitwarden.com/#/recover-delete" doesn't take you anywhere except into your general vault. There is nothing there regarding recovery or deletion.

**Comment by fschillingeriv** [comment]
Huh, would you mind trying it again? The link seems to be working fine for me on several different browser and devices.
![Screen Shot 2021-02-24 at 5 03 30 PM](https://user-images.githubusercontent.com/69817454/109072089-8c080180-76c2-11eb-8c6e-f8cd222e67fe.png)

**Comment by djsmith85** [comment]
I've also just tried it via the help site and the provided link and both navigate to the correct site, shown in the image @fschillingeriv provided.

**Comment by fschillingeriv** [comment]
Thanks @djsmith85. I'm going to close this issue, I hope you're able to reach that page @as232.
