### ISSUE TITLE
Improvement: add "open website" button near the URI

### ISSUE THREAD

**Issue by mt62418** [bitwarden/help#428]
Improvement: add "open website" button near the URI

**Comment by fschillingeriv** [comment]
There's a **Launch** button next to the URI fields in all Bitwarden apps, here's a shot of it in the Web Vault:

![Screen Shot 2021-02-25 at 8 09 11 AM](https://user-images.githubusercontent.com/69817454/109158151-fcedfe80-7740-11eb-887f-a07c01102b7c.png)

For Feature Requests, please post them in [the community forums](https://community.bitwarden.com/t/about-the-feature-requests-category/12), where they'll be seen. Product & Engineering aren't actively monitoring this repository, as it's exclusively for the documentation site.
