### ISSUE TITLE
Mistake in about-sso page

### ISSUE THREAD

**Issue by Jipje** [bitwarden/help#435]
Under the header Self-Hosting Requirements, the link with the text _Updating your Self-Hosted Installation_ links to the page: https://bitwarden.com/help/updating-on-premise 
Which gives a 404 error

**Comment by vachan-maker** [comment]
Thanks for reporting this issue
Pull Request linked
Actual Link: https://bitwarden.com/help/article/updating-on-premise/

**Comment by vachan-maker** [comment]
No worries
Closed mine
