### ISSUE TITLE
Provide a list of the licensed features

### ISSUE THREAD

**Issue by eightnoneone** [bitwarden/help#438]
Suggestion or Edit for: bitwarden.com/help/article/licensing-on-premise/

The linked [what-plan-is-right-for-me](https://bitwarden.com/help/article/what-plan-is-right-for-me/) provides helpful information for determining the appropriate plan in the context of feature needs. It does not provide a concise list of what _is_ and _is not_ a licensed feature. 

As a decision-maker evaluating self-hosting and open-source solution, having a concise list of what "some features" is would be helpful.

**Comment by tgreer-bw** [comment]
@eightnoneone this article should cover the items you're looking for: https://bitwarden.com/help/article/about-bitwarden-plans/

@fschillingeriv would probably be good to add that link to the 'what plan is right for me' page, too :-)

**Comment by fschillingeriv** [comment]
Yeh, I'm thinking based on @eightnoneone 's insight that /about-bitwarden-plans/ is a better article to link to in most cases, /what-plan-is-right-for-me/ may have a somewhat narrower window of relevance.
