### ISSUE TITLE
please document this smtp trust server option

### ISSUE THREAD

**Issue by SvenMW** [bitwarden/help#44]
Hi,

i just found this via extensive googling and almost giving up in your issue tracker:

If you want to ignore the untrusted certificate failure and blindly trust the server (not recommended) you can now set the following in >= 1.30.0

in `./bwdata/env/global.override.env`:

```
globalSettings__mail__smtp__trustServer=true
```

Then restart with `./bitwarden.sh restart`

_Originally posted by @kspearrin in https://github.com/bitwarden/server/issues/451#issuecomment-472846765_

I could not find this in the docs anywhere, I guess this option should be added here:

https://help.bitwarden.com/article/install-on-premise/#post-install-environment-configuration

**Comment by fschillingeriv** [comment]
Check out our (relatively) new article on server environment variables: https://bitwarden.com/help/article/environment-variables/.
