### ISSUE TITLE
New instructions to enable auto-fill

### ISSUE THREAD

**Issue by davidbeers** [bitwarden/help#440]
Suggestion or Edit for: bitwarden.com/help/article/auto-fill-ios/

Currently the instruction under the "Enable auto-fill in Settings" heading reads:
1. Tap ⚙ Settings on your iOS device
2. Tap Passwords

Best to clarify that you are referring to the Settings app. More importantly, there is no "Passwords" option in the Settings app any more. There are instead two options in the Settings menu that sound similar to "Passwords": "Touch ID and Passcode" and "Passwords and Accounts." You want users to scroll past the first one and tap the second.

Corrected instruction:
1. Launch the the iOS "Settings" app
2. Tap "Passwords and Accounts"
...

**Comment by fschillingeriv** [comment]
@davidbeers Can you confirm what version of iOS your device is on? I just updated to 14.4 to do due diligence and found that the option remains only **Passwords**, screenshot below:

![IMG_2794](https://user-images.githubusercontent.com/69817454/109541272-a01c7c00-7a91-11eb-9144-13009f13cbe4.jpeg)
