### ISSUE TITLE
Two Trivial Typos

### ISSUE THREAD

**Issue by eu90h** [bitwarden/help#444]
First
-------
Suggestion or Edit for: bitwarden.com/help/article/account-encryption-key/
The [rotate your encryption key](https://bitwarden.com/help/article/account-encryption-key/#rotate-your-encryption-key) section says in the first line, "Rotating your account’s encryption key generates a new encryption key that is used to re-encryption all Vault data." 

This should read, "Rotating your account’s encryption key generates a new encryption key that is used to re-encrypt all Vault data."

Second
-----------
When setting up an emergency contact, the email message sent to notify the grantee that they've been confirmed as an emergency contact says in the first sentence, "This email is to notify you that you have been confirmed as an emergency access contect for [NAME]."

This should instead say, "This email is to notify you that you have been confirmed as an emergency access contact for [NAME]."

Thanks for taking a look. Appreciate the service.

**Comment by vachan-maker** [comment]
Thanks for reporting this issue.

**Comment by fschillingeriv** [comment]
Awesome finds @eu90h, and thanks for jumping in @vachan-maker. Going to close this issue, as server/#1172 is where this'll get resolved.
