### ISSUE TITLE
"Clone Item" seems to be removed from web vault

### ISSUE THREAD

**Issue by chrschmitz** [bitwarden/help#446]
Suggestion or Edit for: bitwarden.com/help/article/managing-items/

The option "Clone Item" seems to be removed from web vault. I see:

- Copy user name
- Copy password
- Start
- Attachments
- Collections
- Delete

![Screenshot](https://user-images.githubusercontent.com/13820940/109458409-0044fb00-7a5d-11eb-8371-3a4e3018c21e.jpg)

**Comment by vachan-maker** [comment]
I can see the Clone Option 
![image](https://user-images.githubusercontent.com/65799568/109468215-4c5e6280-7a92-11eb-8120-f5b3ad177bc9.png)

**Comment by vachan-maker** [comment]
Also, please do note that this repository is for the help documentation.
The repository for the web vault is https://github.com/bitwarden/web

**Comment by chrschmitz** [comment]
This was a comment for the help documentation.

![Bildschirmfoto 2021-03-01 um 09 16 12](https://user-images.githubusercontent.com/13820940/109469800-d268b200-7a6e-11eb-8095-3a165ae4db4a.jpg)

**Comment by vachan-maker** [comment]
> 
> 
> This was a comment for the help documentation.
> 
> ![Bildschirmfoto 2021-03-01 um 09 16 12](https://user-images.githubusercontent.com/13820940/109469800-d268b200-7a6e-11eb-8095-3a165ae4db4a.jpg)

Are you self hosting?
If so, you will need to update the web vault

**Comment by chrschmitz** [comment]
No, I am using your cloud solution.

**Comment by chrschmitz** [comment]
I may have found the problem. The option does not exist in items stored in collections. As this option exists in the client application, I do not know, whether I should report this as a bug, or -- if this is per design -- whether you should mention this special case in the help documentation.

**Comment by chrschmitz** [comment]
Yes, I fell into the trap that "sharing" is not really sharing but the transfer of ownership. I thought that I still own a shared item.
