### ISSUE TITLE
Enhancement Request: Allow for adding a password to Secured Notes

### ISSUE THREAD

**Issue by dmcmaste** [bitwarden/help#455]
I'd like to request an enhancement request to allow for adding a password to open Secured Notes

Thanks!

**Comment by fschillingeriv** [comment]
@dmcmaste Thanks for getting in touch! This repository is specifically for Bitwarden's Help Center, located at bitwarden.com/help.

To make feature requests for our apps, see https://community.bitwarden.com/t/about-the-feature-requests-category/12
