### ISSUE TITLE
LastPass Import File Format Error

### ISSUE THREAD

**Issue by JTRemington** [bitwarden/help#458]
Following [the instructions](https://bitwarden.com/help/article/import-from-lastpass/) to import data from LastPass results in the following error:

<img width="323" alt="Data is not formatted correctly" src="https://user-images.githubusercontent.com/23303188/110187257-f876b500-7dd4-11eb-9d38-dccd5f8538cf.png">

The error message instructs the user to check the file and try again. The copy/paste function yields the same results.

troubleshooting documentation is needed for this issue. There may be "secure notes" in the LastPass export, or saved credit/debit card information - both of which appear to break the import, though there might also be other issues. The special types, such as secure notes, are interlaced with standard username/password data and not neatly sorted into a special section; apparently by date of creation.

**Comment by fschillingeriv** [comment]
Just ran a quick test with a combination of Logins, Cards, and Secure Notes - everything imported fine, so it would seem this has been resolved by some of the work done on the LP importer earlier this year.

Closing this issue.
