### ISSUE TITLE
Import LastPass CSV Grouping Example Consistency

### ISSUE THREAD

**Issue by soyfrien** [bitwarden/help#459]
Hello,

The `grouping` datum limit [example](https://bitwarden.com/help/article/import-from-lastpass/) for the free version can introduce confusion by changing more than just the `grouping` datum, but also the `login` and `password`. Readers may wonder why those changes were added, or worse, consider them necessary.

![image](https://user-images.githubusercontent.com/3385925/110210424-acbd1d80-7e5f-11eb-9a1d-c5bba58753a1.png)
_`login` and `password` should not be changed to `test,test`, as users may blindly follow this change._

**Comment by fschillingeriv** [comment]
Good catch @soyfrien - you're right, that's very confusing
