### ISSUE TITLE
No cards info in exported csv

### ISSUE THREAD

**Issue by panlibra** [bitwarden/help#460]
no cards information found in csv file when exported the whole vault while did find in json file.  Hope it be fixed.

**Comment by Greenderella** [comment]
Hi @panlibra,

This is the intended behaviour. Bitwarden recommends using .json for a more complete option for standard backup procedures as .csv exports will not export Cards or Identities.

More information here: https://bitwarden.com/help/article/export-your-data/

**Comment by fschillingeriv** [comment]
Thanks @Greenderella! Closing this issue 😄
