### ISSUE TITLE
Directory Connector Azure AD: Deleted users causing 404 error when testing includeGroup

### ISSUE THREAD

**Issue by Noxxehlicious** [bitwarden/help#464]
Just requesting to add a note to https://bitwarden.com/help/article/azure-active-directory/
I was using the Test feature of the Bitwarden Directory Connector and kept running into an error when using the SyncUser "includeGroup" function. "Resource <objectID> doest not exist or one of its queried referenced-property objects are not present."
I found out that the Directory Connector checks the group for deleted users, causing the above error to appear. Permanently deleting the users or restoring the users fixes the error. 
I think a note mentioning to check or to make sure that the deleted users area is clear when testing would be helpful for others in the future.

**Comment by MGibson1** [comment]
Thank you for this! This issue should be fixed in the next release of BWDC bitwarden/directory-connector#99. I'll leave the issue open in case @fschillingeriv wants to update documentation for previous versions or until we have the latest released, which should be very shortly
