### ISSUE TITLE
Two-step Login via Authenticator

### ISSUE THREAD

**Issue by DoodlesEpic** [bitwarden/help#467]
At https://bitwarden.com/help/article/setup-two-step-login-authenticator/ it's not really obvious that if you already had another 2FA enabled, both will still work, and thus "Losing access to your authenticator app can permanently lock you out" isn't exactly true, as you are able to choose which 2FA method to use at login. 

So "unless you write down and keep your Two-step Login Recovery Code in a safe place" could also have "or you have another 2FA method enabled". Small detail but I think it would make the help document clearer.

**Comment by fschillingeriv** [comment]
Great suggestion, @DoodlesEpic! I happen to be working in these articles already today, so I'll update them with your suggestion now.
