### ISSUE TITLE
Reminder to check for still logged-in devices

### ISSUE THREAD

**Issue by jaker-dotcom** [bitwarden/help#472]
Before deleting the account users should check other devices if they're still logged in. Exporting vault isn't possible without master password either but most important passwords can be manually copied or written down by hand. 

Referring to this page: https://bitwarden.com/help/article/forgot-master-password/

**Comment by fschillingeriv** [comment]
Thanks @jaker-dotcom, a note on this is in the "Before deleting your account:" tip pane, pictured below: 

![Screen Shot 2021-03-11 at 12 39 06 PM](https://user-images.githubusercontent.com/69817454/110830192-f003fb80-8266-11eb-9d5b-bfa2d6084ccf.png)

**Comment by jaker-dotcom** [comment]
Oh I guess I was skimming too fast.
Great that you thought about it anyways!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
