### ISSUE TITLE
Step 3 on the export, how to prevent it printing to your screen vs. a .csv

### ISSUE THREAD

**Issue by daveinfla** [bitwarden/help#475]
What I have found is if you keep the Lastpass plugin active while doing the export you'll get a .csv file to download. If you removed the plugin before you try to export from the Lastpass vault it will print to the screen.

This was on Windows 10 in both Chrome and Brave.

Dave

**Comment by fschillingeriv** [comment]
Interesting! I'm going to leave the article as-is so folks have instructions for both styles, but that's good to know!
