### ISSUE TITLE
i need instructions for miui 12.0.3

### ISSUE THREAD

**Issue by apometron** [bitwarden/help#497]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by vachan-maker** [comment]
Can you provide more details? What instructions are you looking for?

**Comment by Greenderella** [comment]
Hi @apometron, have you taken a look on our Help Center about how to enable autofill on Android: https://bitwarden.com/help/article/auto-fill-android/ ? 

If you keep experiencing issues with your accessibility features on MIUI, please post it on our Community Forum on the [User-to-User support section](https://community.bitwarden.com/c/support/6), or contact the Customer Success team using the following contact form: https://bitwarden.com/contact/
