### ISSUE TITLE
Send Privacy Feature Request

### ISSUE THREAD

**Issue by farukyo** [bitwarden/help#498]
The new **"Send"** feature is brilliant, but it lacks a little feature in my opinion.
![resim](https://user-images.githubusercontent.com/52610005/111518576-3e356500-8767-11eb-84bb-a809913acccc.png)
![resim](https://user-images.githubusercontent.com/52610005/111519577-4d68e280-8768-11eb-99a0-e09d22aa63bf.png)
As shown above there are no **"hide my e-mail"** option. It would be better if we have an option to hide our e-mail. Thanks. ❤️

**Comment by fschillingeriv** [comment]
Thanks for getting in touch, @farukyo! This repository is solely for the documentation side of Bitwarden, for feature requests we use the community forums.

In fact, the feature you're describing is already requested and on the team's radar(https://community.bitwarden.com/t/allow-hiding-bitwarden-email-from-send/2683). Go ahead and give it a vote!
