### ISSUE TITLE
Better Default Item Names

### ISSUE THREAD

**Issue by NWalker1208** [bitwarden/help#507]
Right now, most if not all new entries default to being named after the URL of the website. It would be better if they automatically used the page title of the website's homepage.

IE: Google instead of google.com

**Comment by Greenderella** [comment]
Thanks for getting in touch, @NWalker1208! This repository is solely for the documentation side of Bitwarden, for feature requests you have our [Community Forums](https://community.bitwarden.com/c/feature-requests/5).
