### ISSUE TITLE
Bitwarden 

### ISSUE THREAD

**Issue by dawgdemi** [bitwarden/help#508]
Suggest an edit, addition, or any other comment specific to the Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by tgreer-bw** [comment]
Hi! What would you like to suggest be changed?
