### ISSUE TITLE
Import: Does the data only stay local?

### ISSUE THREAD

**Issue by richb-hanover** [bitwarden/help#515]
When importing data, and on the [Import data into your Vault](https://bitwarden.com/help/article/import-data/#import-to-your-personal-vault) page, I immediately wondered:

> Wait a minute - I'm uploading my unencrypted data to this web page. Does the page send the data to the Bitwarden servers to get back the encrypted vault?

I imagine not, but it would be really good to emphasize that the unencrypted password information stays local to / never leaves my computer...

**Comment by richb-hanover** [comment]
I want to be clear what I'm requesting: The import page handles unencrypted data. As a computer professional, I always get nervous whenever my data sits around unencrypted. 

The documentation somehow should convey:

* The import page reads the imported password information, encrypts it and adds those items into the vault.
* The unencrypted password information is processed solely by this web page. It never leaves your computer.
* Items that have been encrypted are added to the vault. That vault is then shared with all your devices.

You don't need to make a big deal of this (no scary messages to alarm new users), but it would be reassuring to have the statement shown in a sidebar/info/how does this work? section.

(I am assuming that the statements above are true. Correct?)

**Comment by fschillingeriv** [comment]
Hey @richb-hanover, sincere apologies for the late response. Yes, you're correct on all points, all the encrypting of your import data happens locally.

If you'd like to see an in-product message to that effect, I'd recommend opening a thread in our [Feature Request Forum](https://community.bitwarden.com/c/feature-requests/5), where others can discuss and vote on it!

As far as Help site documentation goes, I'll more than happily add a note to reassure future importers. Cheers!
