### ISSUE TITLE
Help Page "I Forgot my Master Password" should mention Emergency Access

### ISSUE THREAD

**Issue by Mrxx99** [bitwarden/help#527]
The article "I Forgot my Master Password" https://bitwarden.com/help/article/forgot-master-password/
does not mention Emergency Access as a way to retrieve access or save the data in the vault when master password was lost.

**Comment by fschillingeriv** [comment]
Good suggestion @Mrxx99. Unfortunately, lots of users come to this article when it's too late and haven't thought ahead to setup EA, but I'll add that that's an option for those lucky/prudent users who do.

**Comment by fschillingeriv** [comment]
Forgot to mention that this was resolved in #585, so closing the issue. Thanks again for the suggestion @Mrxx99!
