### ISSUE TITLE
Feature request in Bitwarden

### ISSUE THREAD

**Issue by SchuurmansP** [bitwarden/help#529]
Hi, is it possible to extend the search also through the notes? I.e in KeyPass it is possible to search for logins with a certain telephone number as second verification or creditcard number. That would be niet.
Thanks

**Comment by Greenderella** [comment]
Thanks for getting in touch, @SchuurmansP ! This repository is solely for the documentation side of Bitwarden, for feature requests you have our [Community Forums](https://community.bitwarden.com/c/feature-requests/5).
