### ISSUE TITLE
Rephrase on Security FAQ page

### ISSUE THREAD

**Issue by Stickyhavr** [bitwarden/help#530]
On the security faq page: https://bitwarden.com/help/article/security-faqs/

Under the question:
Q: What happens if Bitwarden gets hacked?

If for some reason Bitwarden were to get hacked and data be leaked despite this, your information is still protected due to strong encryption and one-way salted hashing measures taken on your Vault data and master password.

The second paragraph reads funny. “Be leaked despite this” should be rephrased.  Maybe just “were leaked” (removing the “despite this”)?

**Comment by go12** [comment]
thanks. we will adjust
