### ISSUE TITLE
Suggestion: Improve article about import from Firefox

### ISSUE THREAD

**Issue by tzdybal** [bitwarden/help#533]
When I tried to follow [import from Firefox instructions](https://bitwarden.com/help/article/import-from-firefox/), I got following error:
```
[2] [Login] "--": The field Password exceeds the maximum encrypted value length of 1000 characters.
```
and passwords were not imported.

After inspecting the file, I noticed that Firefox puts `chrome://FirefoxAccounts` record into exported file, and it contains JSON data instead of password (looking at 74% of negative feedback on above-mentioned article, I guess I'm not the one with this problem).

Simple walk-around is to remove line starting with `"chrome://FirefoxAccounts" ` - then file is imported correctly. 

My suggestion is to mention this walk-around in [help article](https://bitwarden.com/help/article/import-from-firefox/).

I also made [PR](https://github.com/bitwarden/jslib/pull/323) to fix this issue completely.

**Comment by Greenderella** [comment]
Hi @tzdybal,

Thank you so much for your contribution! It seems like it's not necessary to mention the walk around anymore on our article thanks to it. Do you think it would be possible to close this issue?
