### ISSUE TITLE
Feature problem - autologin

### ISSUE THREAD

**Issue by brnvogel** [bitwarden/help#535]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by Greenderella** [comment]
Thanks for getting in touch, @brnvogel  ! This repository is solely for the documentation side of Bitwarden, for feature requests you have our [Community Forums](https://community.bitwarden.com/c/feature-requests/5).
