### ISSUE TITLE
Add email as field

### ISSUE THREAD

**Issue by evaleaf** [bitwarden/help#546]
I would like to suggest to add a specific field for the email. 
Many times it happens I have to store both my email and my username. And all the time I have to add a personalized field for email.
Having stored the email can be helpful whuen recovering a password or in login.

**Comment by tgreer-bw** [comment]
Hi! 

This repo/issues are for feedback around content at [bitwarden.com/help](https://bitwarden.com/help) -  specifically, things like updates, typos, clarification, addition to documentation, etc. We do have a great community site at https://community.bitwarden.com where you can submit feature requests - luckily, [this request has already been submitted](https://community.bitwarden.com/t/add-username-and-email-as-separate-entries/5808) - feel free to join the forums and vote for this feature, too!

In the meantime, it is possible to add a [custom field](https://bitwarden.com/help/article/custom-fields/) with your email in it to any item you choose 👍
