### ISSUE TITLE
Creating Subfolders for storing passwords 

### ISSUE THREAD

**Issue by alyssontecinf** [bitwarden/help#554]
Hi, There.

I'm here to suggest the creation of subfolders for storing passwords in BitWarden because today I can't do this.

**Comment by tgreer-bw** [comment]
Hi! 

Thanks for the feedback! Today we support nested folders that are displayed like sub-folders.

https://bitwarden.com/help/article/folders/#create-nested-folders

If you'd like additional functionality, please sign up for our forums here: https://community.bitwarden.com and see if an existing request fits your needs. If so, you're able to vote for it. If you can't find anything that matches what you'd like to see, feel free to create a new topic.
