### ISSUE TITLE
Missing topic "change-your-master-password/#rotating-your-accounts-encryption-key"

### ISSUE THREAD

**Issue by n-zhi** [bitwarden/help#557]
On the page https://vault.bitwarden.com/#/settings/account there is a section of changing master password.
![Changing_master_password](https://user-images.githubusercontent.com/75691177/115468233-7551d700-a23b-11eb-8350-f393fcb52ac7.png)
At the bottom of this section there is a checkbox about rotation of encryption key. Nearby there is a question icon that leads to the page
https://help.bitwarden.com/article/change-your-master-password/#rotating-your-accounts-encryption-key
But there is no such section on the "change-your-master-password" page.

**Comment by vachan-maker** [comment]
Thanks for reporting this issue. Good Find.

**Comment by fschillingeriv** [comment]
Closing this issue, as @vachan-maker & the team redirected the ? to the new link: https://bitwarden.com/help/article/account-encryption-key/#rotate-your-encryption-key
