### ISSUE TITLE
Critical problem in the search of the various recorded items

### ISSUE THREAD

**Issue by etruskus** [bitwarden/help#559]
Hello, I recently decided to leave Keeper to switch to your useful app and I am happy with my choice. Unfortunately, however, I also noticed a not insignificant pejorative factor. When I searched on Keeper, it found all the keywords contained within the various records, for example in the notes. Instead with Bit Warden, from what I have seen, it is possible to search only in titles. This lack has also been noticed by several of my friends who, on my advice, have switched to Bit Warden and for this reason, unlike mine, are planning to return to Keeper soon ... Many people record data on the notes, and they would be useful that the search finds those keywords. Why don't you quickly implement this key feature that would surely be appreciated by all users? It would really be essential. 
I would really appreciate it if instead of reassuring me that my request is being considered, you could honestly let me know if you are really working on this feature or if you are not interested in doing so in the short term.
Thank you.
Stefano

**Comment by Greenderella** [comment]
Thanks for getting in touch, @etruskus  ! 

You may want to search how to perform a full-text search that includes the Notes field: https://bitwarden.com/help/article/searching-vault/#construct-a-full-text-search

Remember that full-text search is available in Web Vaults, Desktop Applications, and Browser Extensions.

Regardless this repository is solely for the documentation side of Bitwarden, for feature requests please refer to our [Community Forums](https://community.bitwarden.com/c/feature-requests/5).
