### ISSUE TITLE
I am perplexed by the handling you have had of my previous message.

### ISSUE THREAD

**Issue by etruskus** [bitwarden/help#562]
Hello,
I work with a Consumer Association in Italy and several friends have pointed out to me, about BitWarden, the criticality of the lack of possibility to do a complete search of the text in the recorded entries, rather than only on the titles, as other rival apps allow, such as Keeper.
And these people have signaled me that they want to uninstall your app, asking me which app allows a full search.
The problem occurs on the app but also on the web vault, because the full text search as you understand it, is certainly not functional and comfortable.
I reported this problem here, after logging into my profile, clicking on "ask for help" and then on "SUGGEST AN EDIT" which in English should have been the right entry to request a change to your software but you have pointed out that this is not the right channel for requests.
I'm not interested in posting in a public group.
However, if you are not interested in allowing direct private contact with the developers or you do not consider it essential to resolve this deficiency that I have reported, despite making you lose potential consumers, I recommend that you at least correct or better specify the various links for contacts and requests for help.
Have a good day.

**Comment by tgreer-bw** [comment]
Hi @etruskus - quite the contrary, we want to hear direct feedback, we just track it in different areas. 

This particular repository is for edits/recommendations/typos in our [documentation](https://bitwarden.com/help), not the product itself, which allows our documentation team to better track items to be changed and edited within our help site.

We have your feedback captured, and if even if you don't want to post any feedback on the community forums  (which we do use for feature requests), there is a thread you can monitor (and vote for) here: https://community.bitwarden.com/t/search-within-and-inside-all-notes/10850
