### ISSUE TITLE
Consider changing layout to aid in explaining auto-fill matching rules

### ISSUE THREAD

**Issue by skube** [bitwarden/help#564]
I always have a difficult time understanding and parsing the URI match rules. Specifically it's a little hard to see immediately what strings match or do not match when presented inline. If they were arranged vertically—say in a table—the differences between scenarios would be more obvious IMHO.

## Current docs show

For example, if the URI value https://www.google.com/page.html uses exact match detection:

**Auto-fill offered** for https://www.google.com/page.html
**Auto-fill not offered** for http://www.google.com/page.html, https://www.google.com/page.html?query=123, or https://www.google.com

## Potential solution?

| https://www.google.com/page.html           | Auto-fill? |
| :----------------------------------------- | ---------- |
| https://www.google.com/page.html           | ✅         |
| http://www.google.com/page.html            | ❌         |
| https://www.google.com/page.html?query=123 | ❌         |
| https://www.google.com                     | ❌         |

**Comment by fschillingeriv** [comment]
Hey @skube, this was an awesome idea! Will be implemented by #597.
