### ISSUE TITLE
Would "Re-create" be more correct than "re-download"

### ISSUE THREAD

**Issue by corey851** [bitwarden/help#572]
Regarding page: https://bitwarden.com/help/article/account-encryption-key/

I found the use of the word "re-download" confusing here.  If you're re-exporting through the web interface then yes, a download is part of the process, but the export can also be done locally from the browser extension or with the desktop application.  
Just my two cents, but I wonder if this would be a little clearer and more general (highlighting my thoughts):

**Re-create** any Encrypted Exports

If you’re using Encrypted Exports to store long-term secure backups, you should immediately **re-create and save** the encrypted export of your Vault data using the new encryption key.

**Comment by fschillingeriv** [comment]
@corey851 I think that makes sense, especially considering the new encryption key factors into the creation of the export, good suggestion!
