### ISSUE TITLE
unlooking passwords

### ISSUE THREAD

**Issue by rdsa5** [bitwarden/help#577]
hi i'm new bitwarden user and i'm having annoying problem which is ￼ when i unlook a password i need to type bitwarden's password everytime it takes so much time to write. so suggest you guys to add feature ￼￼unlooking by face id (as apple ecosystem￼ user ) it take less time and effort and easier to use , faster for us as users

in prosess of learning english.

**Comment by tgreer-bw** [comment]
Thanks for the comment! We actually do support Face ID:
