### ISSUE TITLE
/help/article/basic-auth-autofill/ needs to be more helpful

### ISSUE THREAD

**Issue by edrandall** [bitwarden/help#579]
https://bitwarden.com/help/article/basic-auth-autofill/

Bitwarden seems unwilling to offer to save a basic-auth site and doesn't provide a drop-down list of matching URLs.
I went to this page to find a solution but am just left confused, the explanation is too terse and uses too much bitwarden jargon.
Please add a couple of examples and clear steps what I must do to get basic-auth filled.

**Comment by needs-coffee** [comment]
you seem to have 2 issues:
**1. save basic auth** 
I assume you mean the banner that appears on a new site that allows you to save a new login to your vault? if so i am not sure this is possible as the basic auth prompt is handled by the browser directly and added to the header not entered into the document. 
**2. getting basic auth filled**
It will only fill out basic auth credentials if there is one (and only one) login saved in your vault with a matching URL. If you have multiple logins for the same site it will not autofill.  When it autofills (at least on chrome) there is no popup, it just passes to the authorized page. 

I just tried it just now with a site that uses basic auth. 
I added the login to the site using the add login button after clicking on the browser extension in chrome.
I clicked on the link that would request basic auth and it logged in without a prompt.

**Comment by edrandall** [comment]
I’m glad it worked on your computer, could you ship it to me please?  Or  perhaps you could share exactly what you did in screenshots.  This seems one case where a picture is worth 1000 words.

 It simply doesn’t work for me and I haven’t even been able to configure it manually to offer a matching site on the dropdown for a manual fill - it stubbornly says “no matching sites”.

**Comment by tgreer-bw** [comment]
Hey folks! if you'd like to continue this discussion (which I think is great and will help folks) - please do so here: https://community.bitwarden.com/c/support/6 - many more eyes on our forums that can help out. 

This repo is for documentation edits (which we have captured and will work on) but since there is no hard and fast issue to resolve here, we'll go ahead and close it.

**Comment by needs-coffee** [comment]
@edrandall 
see the gif attached for chrome. I also tried this with 2 logins saved for the domain and the basic auth window appears again (no autofill) so there must be one and only one match for the URL.

![saving_basic_auth4](https://user-images.githubusercontent.com/10763991/118139724-90a99f80-b3ff-11eb-88d0-86989e3a2ead.gif)

**Comment by tgreer-bw** [comment]
Thanks! I think it would be a nice touch. @fschillingeriv - thoughts?

**Comment by fschillingeriv** [comment]
@tgreer-bw Agreed! That'd be a fantastic addition @needs-coffee, awesome idea!

**Comment by needs-coffee** [comment]
see PR #600
