### ISSUE TITLE
Recommend folder/user in installation instructions

### ISSUE THREAD

**Issue by Zauberfisch** [bitwarden/help#59]
Currently, the installation instructions have a [note](https://github.com/bitwarden/help/blob/master/_articles/hosting/install-on-premise.md#install-bitwarden) saying `All Bitwarden assets will be installed in the ./bwdata directory relative to where the main Bitwarden script resides`.

I think that should be extended to recommend which folder one should use, and if applicable if that should be done with a specific user (or if those files should be owned by a specific user)

**Comment by kspearrin** [comment]
This depends on how you want to install it. We make no recommendations on administration of the server. I would probably install it under a user instead of root.

**Comment by Zauberfisch** [comment]
But that's exactly my point. Many install scripts expect to be run as root.

So if running as a non-root-user is an option, I think that should be documented.

**Comment by kspearrin** [comment]
Our install instructions don't mention anywhere that things have to be run as root, so I don't know why users would assume that?

**Comment by Zauberfisch** [comment]
It is common practice for server applications to be installed globally and register some sort of service (eg systemd). Those steps usually require elevated privileges. So it's not uncommon that installations will only work with sudo.

Obviously one can just "trial and error" this and see if it works with a user nor not. My argument is that the purpose of the documentation is so that users do not have to "just try and see what happens".

**Comment by fschillingeriv** [comment]
Closing this issue, as the documentation was updated accordingly quite some time ago - https://bitwarden.com/help/article/install-on-premise-linux/#create-bitwarden-local-user--directory.
