### ISSUE TITLE
typo - Custom Fields documentation

### ISSUE THREAD

**Issue by needs-coffee** [bitwarden/help#591]
[https://bitwarden.com/help/article/custom-fields/#custom-fields-for-keys](https://bitwarden.com/help/article/custom-fields/#custom-fields-for-keys)

>  Tip
> Character limits for custom field values are imposed on the post-encryption character count. For example, a 3383-character RSA-**_2096_** Private SSH key would grow to about 4400-characters when it’s encrypted and stored in your Vault.
> 

Above tip box on the custom fields page should state RSA-4096 not RSA-2096.

**Comment by fschillingeriv** [comment]
Nice catch @needs-coffee, resolved by #592.
