### ISSUE TITLE
only desktop is mentioned on The browser extension tab for biometric login help page

### ISSUE THREAD

**Issue by zylstra** [bitwarden/help#599]
On the biometric login help page I want to learn about how to log in with biometrics on my mobile Firefox browser.  But when I read the article it only talks about desktop, on the browser extension tab.

**Comment by tgreer-bw** [comment]
Great question!

Firefox mobile can technically install the browser extension, but biometrics are only supported on desktop, since they require the desktop app to be installed.

**Comment by zylstra** [comment]
Why would Bitwarden not support biometrics on mobile?  Phones are generally even more biometric-friendly than desktops.

And why, if Bitwarden does not support biometrics on mobile Firefox, would it include an option to enable it?

**Comment by tgreer-bw** [comment]
Mobile supports biometrics on the Android app, not the FF browser extension. 

Mobile FF allows the installation of Desktop extensions (like Bitwarden) - which causes this confusion sometimes.

**Comment by tgreer-bw** [comment]
https://bitwarden.com/help/article/biometrics/ for more info 😁

**Comment by zylstra** [comment]
Yeah, that's the exact page I referred to in my original post.

The confusion is caused by Bitwarden's mobile Firefox add-on having a checkbox for biometrics that is non-functional.  ... Or are you saying that it should be functional?

I just tried logging into a site on mobile Firefox.  Bitwarden asked for biometrics and logging in worked!  ... But with the "Unlock with biometrics" option in mobile Firefox add-on unchecked.  :/  ... Or is it the mobile _non_-Firefox Bitwarden app that is filling in pages in Firefox now?

**Comment by tgreer-bw** [comment]
The biometrics you saw were running from the Bitwarden Android app, which is 100% ready to go for Biometrics. 

The browser extension you're referencing actually is **not** mobile. Firefox is the only mobile browser I am aware of that allows the installation of desktop browser extensions. It's a nice option, but it's definitely not intended as the main use-case for mobile devices.

**Comment by zylstra** [comment]
OK, that clears up some stuff.  And knowing that Firefox Android add-ons are the same as desktop add-ons clears up more.

Is the Bitwarden Android app as effective at filling in website login data as the mobile Firefox add-on?  If so, then I should delete the mobile Firefox add-on, correct?

It would be great if Bitwarden explained all this in their help article, or better yet, designed the app/add-on so that there is no confusion from the beginning.
