### ISSUE TITLE
Firefox data storage location is no longer accurate

### ISSUE THREAD

**Issue by setyb** [bitwarden/help#60]
The data storage location for Firefox is no longer accurate as presented in:
https://help.bitwarden.com/article/where-is-data-stored-computer/

**Comment by kspearrin** [comment]
Which platform? What are the new paths?

**Comment by setyb** [comment]
I'm guessing all platforms.  I verified on Windows 7, 8.1, and 10.

I'm a little concerned; do you not have Firefox installed for testing?

I ask (with kind intent, not trying to be unfriendly or anything like that) because I find bitwarden on Firefox to be a little quirky with how the popup refreshes after edits.  I figured that it was by design or the best the was possible, but now I wonder if Firefox is being regularly used during testing, especially UI testing.

**Comment by kspearrin** [comment]
Yes, I use Firefox. Do you know where extension data is stored now?

**Comment by setyb** [comment]
Great to hear.  I'll check.  Give me 5-10 minutes.

**Comment by setyb** [comment]
Kyle, I hold your skills and knowledge in high regard.

I figured there is little chance I know something that you don't!

Perhaps I need to work on my self-esteem. :)

As of the current Firefox general release (71.0; note that 72.0 will be released in 2 days) bitwarden data is stored in `..\storage\default\moz-extension+++[UNIQUE-GUID]` within the currently active Firefox profile folder (which can be located wherever the user specifies).

AFAIK, this should be cross-platform.

IIRC, I'm almost sure that [UNIQUE-GUID] will be a unique GUID for every Firefox profile.  It's a clever Mozilla technique to increase security.

**Comment by setyb** [comment]
My best attempt to resolve this issue is https://github.com/bitwarden/help/pull/62

I hope this helps!
