### ISSUE TITLE
Configuring Keyboard Shortcuts for Edge Browser possible

### ISSUE THREAD

**Issue by bvanderwerff** [bitwarden/help#604]
Hi team,

On "https://bitwarden.com/help/article/auto-fill-browser/", in the chapter: Configuring Keyboard Shortcuts",  it is mentioned that shortcuts cannot be edited for Edge browser. However, I am currently on Edge browser v90 version and am able to set the Bitwarden shortcut to Ctrl + Shift + L via "edge://extensions/shortcuts". Yeeeh!

Kind regards, 

Brian

**Comment by tgreer-bw** [comment]
It's the older non-chromium Legacy Edge that won't let you edit them, but thankfully the new Edge has all the Chrome bells and whistles 😄
