### ISSUE TITLE
WebAuthn instructions need to be documented

### ISSUE THREAD

**Issue by PacoBell** [bitwarden/help#608]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by fschillingeriv** [comment]
@PacoBell have you seen https://bitwarden.com/help/article/setup-two-step-login-fido/? If that's not what you're looking for, perhaps you can provide more info on the documentation you'd need?
