### ISSUE TITLE
Definition of URL constituents

### ISSUE THREAD

**Issue by skube** [bitwarden/help#609]
Perhaps it's common knowledge for some, but it might help others to actually define and show the different parts of a URL _before_ referring to them. 

For example, with an image like:

![URL parts](https://user-images.githubusercontent.com/146396/119137105-72026480-ba0e-11eb-86a1-49ff75ec6149.png)

**Comment by fschillingeriv** [comment]
Good thinking @skube. It seems to me the place this would be most helpful is https://bitwarden.com/article/uri-match-detection/#match-detection-options, agree?

**Comment by skube** [comment]
Yes! Thought it seems the link you provided was meant to be:
https://bitwarden.com/help/article/uri-match-detection/#match-detection-options

**Comment by fschillingeriv** [comment]
Yep, it is indeed!

**Comment by skube** [comment]
Feel free to use the image provided or if you want it tweaked in any way, I can update.
