### ISSUE TITLE
CRITICAL CLI - Directory Connector Info Missing from Docs

### ISSUE THREAD

**Issue by sburns90** [bitwarden/help#630]
The BW Directory Connector CLI documentation is missing come key information.
The article here:
https://bitwarden.com/help/article/directory-sync-cli/

Does not include the instructions of adding the following environment variable
_export BITWARDENCLI_CONNECTOR_PLAINTEXT_SECRETS=true_

Doing this prevents the almost inevitable occurance of: 
_'Failed to execute child process "dbus-launch" (No such file or directory)'_
error that occurs when attempting to run the command:
_bwdc config_

That information is from here from the Founder and CTO.
https://github.com/bitwarden/directory-connector/issues/24#issuecomment-508810377

**Comment by fschillingeriv** [comment]
Hey @sburns90, there's a bit on that in another article (https://bitwarden.com/help/article/directory-sync-shared/#secret-storage-in-headless-environments), but you make a good point - this deserves mention in https://bitwarden.com/help/article/directory-sync-cli/ as well.

Thanks for bringing it up!
