### ISSUE TITLE
The end of the tutorial Get Started with Organizations is unclear.

### ISSUE THREAD

**Issue by jimrandle** [bitwarden/help#635]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by jimrandle** [comment]
The last step in this tutorial is to create a new login. It is unclear what the new login will be used for. Will each sharer have to login to it to see the shared items? Is it just a holding spot to keep shared items? how do the two users put shared items into the vault? Please help me understand the usage. Thanks.

**Comment by fschillingeriv** [comment]
Hey @jimrandle, point well taken! We've added (#650) some context to the referenced section, hopefully that'll clear up what's achieved through 'sharing'. Cheers!
