### ISSUE TITLE
keep it organised

### ISSUE THREAD

**Issue by vimal220892** [bitwarden/help#637]
while displaying the passoords show it like this in each folders as it will be easy to search and find and 
![45456454](https://user-images.githubusercontent.com/85925789/122008286-7b48dc00-cdd6-11eb-9588-a1bb3a19086d.PNG)

**Comment by Greenderella** [comment]
Thanks for getting in touch, @vimal220892  ! This repository is solely for the documentation side of Bitwarden, for feature requests you have our [Community Forums](https://community.bitwarden.com/c/feature-requests/5).
