### ISSUE TITLE
Search bar glitch

### ISSUE THREAD

**Issue by anthonyolson8404** [bitwarden/help#638]
When using the search bar on the top of bitwarden with a new tab in chromium (kiwi version), the search bar will allow me to type two characters and then stops allowing further text, touching in the search bar field will allow for further entry, but it is consistent that Everytime after two characters the search bar deselects.

**Comment by fschillingeriv** [comment]
Hey @anthonyolson8404, are you experiencing this bug with https://bitwarden.com/help (Help Center) or https://vault.bitwarden.com (Web Vault)? If Web Vault, please open an Issue in github.com/bitwarden/web!
