### ISSUE TITLE
Undo emergency access & return to normal

### ISSUE THREAD

**Issue by Function-10** [bitwarden/help#640]
Please can you add some more clarification to the Emergency Access help article (https://bitwarden.com/help/article/emergency-access/#user-access)

> View: When an emergency access request is granted, this user is granted view/read access to all items in your personal Vault.

Please can you clearly & explicitly state that the grantee will be able to view the passwords or not?

> Tip As the grantor, you may revoke access to a grantee with View access at any time

The article is structured in the logical order of steps. At the end, can you please add a section to "undo" the granted access & revert back to a state where the grantee is once again an emergency contact and doesn't have view or take over access anymore. This emergency access must be requested again because the emergency has passed & life has returned to normal.

**Comment by fschillingeriv** [comment]
Hey @Function-10, awesome idea! We've added (#650) a section on the end of that article describing the steps to 'reclaim exclusive access'. Please note, it's a different procedure depending on whether your trusted contact is granted **View** or **Takeover** access.
