### ISSUE TITLE
Export Vault Suggestion

### ISSUE THREAD

**Issue by Shopper64** [bitwarden/help#666]
Please explain where these exports end up by default?  I can't find mine.

**Comment by fschillingeriv** [comment]
Hey @Shopper64, can you provide some information about which client app you're exporting from? In brief testing, most will prompt you to pick a destination (so, no 'default') but there are some cases where that's not true. In those cases, it'll probably be your browser or system settings picking the destination, so I might be able to help you find it with a bit more info.

**Comment by fschillingeriv** [comment]
Hey @Shopper64, haven't heard from you in a while so I'm going to close this issue. If you continue to have issues, please reach out to Customer Support from https://bitwarden.com/contact.
