### ISSUE TITLE
Explain how this whole process works if you change your master password but don't rotate encryption keys.

### ISSUE THREAD

**Issue by Narvey** [bitwarden/help#669]
https://bitwarden.com/help/article/what-encryption-is-used/ explains how salting and hashing works when you first create your vault, but I'm pretty sure it doesn't work that way after you change your master password (unless you also rotate the encryption key), or the derived encryption key would be wrong.
Please explain in the article what happens when you do **not** rotate the key when changing the password.

**Comment by tgreer-bw** [comment]
@Narvey the master password-derived key is used to encrypt/protect the vault key, so changing the master password doesn't require a change of the protected (vault) key, or re-encryption of items within your vault.

I added a note to the help page to point to the security whitepaper, [here](https://bitwarden.com/images/resources/security-white-paper-download.pdf) - page 10 has a diagram that should clarify for you :+1:
