### ISSUE TITLE
Enter key site launch

### ISSUE THREAD

**Issue by LuEcl** [bitwarden/help#678]
I'm using the Firefox add-on.
When I start to type a site name in the search window and the correct entry appears, I would like to be able to use the keyboard to select & launch the site.
Currently I have to stop using the keyboard, reposition my hand to the mouse, find the launch button and press. Would be much more convenient to simply select & press enter.

p.s. - I have just switched from Lastpass and so far really prefer this product.

**Comment by needs-coffee** [comment]
this is the GitHub page for editing the [help pages](https://bitwarden.com/help/) only not for user support.
Bugs/improvements to the browser extension should be submitted here - https://github.com/bitwarden/browser/issues
Feature requests should be submitted here - https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.

@fschillingeriv or @tgreer-bw suggest closing this.

**Comment by tgreer-bw** [comment]
Thanks @needs-coffee! Closing this, but definitely add your comments to our forums @LuEcl 😎
