### ISSUE TITLE
Generator Length Selection

### ISSUE THREAD

**Issue by kadirmustafa** [bitwarden/help#681]
On the mobile app, when i wanted to generate a password it is very hard to position length of the password. Can you put editable text box to change it easily.

**Comment by needs-coffee** [comment]
This is the GitHub page for editing the online [help pages](https://help.bitwarden.com) only not for user support.

- Bugs/code improvements to the mobile app should be submitted here - https://github.com/bitwarden/mobile
- Feature requests should be submitted to the community forum here where other members can comment and vote on your suggestion - https://community.bitwarden.com/c/feature-requests
