### ISSUE TITLE
Password Hint

### ISSUE THREAD

**Issue by ljbachman12** [bitwarden/help#686]
Please specify (or tell me where I can find out) how I can change my "password hint" WITHOUT changing my master password (I have not trierd it, but I assume that if/when I change my master password I would be prompted to provide a new hint. Right?).

I realized, when I needed it, that I had made typographical errors (I am really BAD at typing) and it took me a while to figure out what the misspelled hint was referring to. When I figured it out, I wanted to correct the (nonobvious) hint.

**Comment by Greenderella** [comment]
Hi @ljbachman12 

In order to change the hint associated with your account, log into the Web Vault (https://vault.bitwarden.com) and go to Settings > My Account > Master Password Hint.
