### ISSUE TITLE
Add instructions for restoring database

### ISSUE THREAD

**Issue by houfu** [bitwarden/help#69]
Currently `_articles/hosting/backup-on-premise.md` writes the following for restoring a backup

> You can read more about SQL Server backup restoration at https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/complete-database-restores-simple-recovery-model/.

This is difficult to follow because it is not bitwarden specific.

Suggestion: Add a new section for restoring a MSSQL database immediately below nightly backup with the following steps.

1. `docker exec` into mssql container
2.  Take note of which backup to restore in the `/etc/bitwarden/mssql/backups/` path
3. Run `sqlcmd`
4. Execute `RESTORE DATABASE` command in vault database
5. Finish

I can create a PR if this is ok.

**Comment by kspearrin** [comment]
PR would be welcomed. Thanks.
