### ISSUE TITLE
Fingerprint passphrase: am I to keep it secret. Is it uses like the passphrase I’ve set up with KuCoin and which arrived on their emails indicating that they are legitimate? Thanks

### ISSUE THREAD

**Issue by graybushman** [bitwarden/help#693]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by needs-coffee** [comment]
this is the GitHub page for editing the [bitwarden help pages](https://bitwarden.com/help/) only not for user support.

Bugs/improvements to the browser extension should be submitted here - https://github.com/bitwarden/browser/issues
Bugs/improvements to the mobile apps should be submitted here -  https://github.com/bitwarden/mobile/issues
Bugs/improvements to the web vault should be submitted here - https://github.com/bitwarden/web/issues
Feature requests should be submitted here - https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.

Other support related questions should be posted here - https://community.bitwarden.com/

----
In answer to your question as [outlined here](https://bitwarden.com/help/article/fingerprint-phrase/) the fingerprint phrase is unique and used to identify that your connection has not been tampered with and is another step to ensure you are validating legitimate requests  - **so yes, keep it secret.**

**Comment by graybushman** [comment]
Thanks so much. 😀
