### ISSUE TITLE
Reduce the size of the autofill service popup 

### ISSUE THREAD

**Issue by sH1222J** [bitwarden/help#700]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

I use it with Samsung Pass. 
reduce the size

**Comment by needs-coffee** [comment]
this is the GitHub page for editing the [bitwarden help pages](https://bitwarden.com/help/) only not for user support.

Bugs/improvements to the mobile app should be submitted here - https://github.com/bitwarden/mobile/issues
Feature requests should be submitted here - https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.

It would be useful for you to post this in the community forum as you will not get a response on this page about your issue :)
