### ISSUE TITLE
Save confirm

### ISSUE THREAD

**Issue by Markuzzo** [bitwarden/help#703]
Please, add a confirm option when I close an editing on existing item.
On Android device it's easy to close the edit windows without save, because the save button is out of window.

**Comment by Greenderella** [comment]
Hi @Markuzzo 

This is the GitHub page for editing the Bitwarden help pages only, not for user support.

Bugs/improvements to the mobile app should be submitted here - https://github.com/bitwarden/mobile/issues
Feature requests should be submitted here - https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.

It would be useful for you to post this in the community forum as you will not get a response on this page about your issue :)
