### ISSUE TITLE
Android timeout for auto logout setting does not work 

### ISSUE THREAD

**Issue by nfrancque** [bitwarden/help#725]
The setting for a timeout before being automatically logged out on the Android app does not work, I am always prompted to log in regardless of the state of the setting. Android 11, app is up to date.

**Comment by needs-coffee** [comment]
This is the GitHub repo for editing the help pages only - not for user support.
Bugs/improvements to the mobile app should be submitted here - https://github.com/bitwarden/mobile/issues
Feature requests should be submitted here - https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
Support can be found here - https://community.bitwarden.com/

What would help is if you provided further information with regards to your app version, mobile phone model and software versions, steps to reproduce and do you mean signed out or the app being locked after a timeout, but please post in the locations in the links above.
