### ISSUE TITLE
Add information about autofill shortcut not working in edge

### ISSUE THREAD

**Issue by douglasparker** [bitwarden/help#726]
A long time ago I suggested adding information about the autofill shortcut not working in edge. This information was added and was extremely helpful for those of us that ran into this issue.

It has since been removed, and people I have recommended to Bitwarden have come to me asking why `Ctrl/CMD + Shift + L ` doesn't autofill in edge.

There is no longer any documentation that I can link them to.

https://bitwarden.com/help/article/keyboard-shortcuts/

**Comment by tgreer-bw** [comment]
Hi @douglasparker! Thanks for the note. We removed the reference since our official support for Edge is now on the Chromium-based version, which works beautifully with Autofill.

We can add a note about the Edge requirements 👍

**Comment by douglasparker** [comment]
> Hi @douglasparker! Thanks for the note. We removed the reference since our official support for Edge is now on the Chromium-based version, which works beautifully with Autofill.
> 
> We can add a note about the Edge requirements 👍 

For whatever reason I had to manually add a shortcut to autofill using Edge on 2 new fresh installs of Windows at `edge://extensions/shortcuts`.

The shortcut to the autofill extension was empty. Previously it was because edge used that shortcut for something else.

By default when I used that shortcut, it opened a new search page and pasted my password into it. This continued to happen until I manually setup the shortcut for Bitwarden.

Not exactly comforting to know that passwords were sent to Google search.

**Comment by douglasparker** [comment]
@tgreer-bw This issue was closed without actually addressing the issue at hand.

Bitwarden doesn't come with an autofill shortcut by default in the new Chromium based Edge. The documentation used to address this, and now it doesn't. Anyone attempting to autofill their password using the documented shortcut will have their password sent to the search engine in raw text.

**Comment by tgreer-bw** [comment]
Hmm, the autofill shortcuts are there by default for most installations, depending on if there are any conflicting shortcuts configured. 

We do provide the instructions in the keyboard shortcut article for how to manage the shortcuts for the browser, too, in the event that the shortcut doesn't behave as intended.

My initial understanding was that the need was documentation letting users know that the legacy didn't support autofill vs, the current version, which does, which is why the issue was closed/resolved with the #727.

Open to other feedback about browser documentation that may help - perhaps it belongs here: https://bitwarden.com/help/article/auto-fill-browser/ ?

**Comment by douglasparker** [comment]
> My initial understanding was that the need was documentation letting users know that the legacy didn't support autofill vs, the current version, which does, which is why the issue was closed/resolved with the #727.

Nope, it's because Microsoft Edge uses Ctrl + Shift + L as an internal shortcut by default, and it still does after switching to Chromium. See more [here](https://support.microsoft.com/en-us/microsoft-edge/keyboard-shortcuts-in-microsoft-edge-50d3edab-30d9-c7e4-21ce-37fe2713cfad).

We need this documentation as it was previously so that users know why autofill isn't working.

I've had a manually copied password get sent to search engines before because of this, which is absolutely terrible.

**Comment by tgreer-bw** [comment]
@douglasparker quick question - did you have autofill on page load enabled? Or had you already copied the password?

If the hotkey was not assigned to Bitwarden and opened a new tab, I'm confused as to how the password would be inserted into the search field.

**Comment by douglasparker** [comment]
> @douglasparker [edit] - apologies - I re-read, I'll see what note we can make.

Just to answer your initial question, I believe I did a manual copy previously and forgot to enable clear clipboard after x seconds.

Then down the road I tried to autofill and it did the default action for Edge which resulted in it being sent to the search engine.

I believe the default setting in Edge is to not clear the clipboard. I am certain that many users have done this in Edge unintentionally.

I think the documentation should show a warning Bitwarden autofill will not work in Edge until the user manually adds the shortcut for Bitwarden.

Even with that information in the docs, I still see people sending their passwords to their default search engine.

I believe I spoke to @kspearrin about this a long time ago and at that time it was deemed impossible for the Bitwarden extension to override this default Edge shortcut.

Having a different default autofill shortcut for Bitwarden also sounds like a poor user experience, so I wouldn't suggest that either.

**Comment by tgreer-bw** [comment]
@douglasparker understood and agreed. I've added a note to help emphasize that default shortcuts may conflict, and links to verify/configure them. 

https://github.com/bitwarden/help/pull/734

Hopefully, this helps when referencing other users who have trouble.

**Comment by douglasparker** [comment]
@tgreer-bw That's perfect! Thank you! 🥳
