### ISSUE TITLE
Upgrade to Premium

### ISSUE THREAD

**Issue by rkalitta** [bitwarden/help#733]
If you have a Basic Free Account, and want to upgrade to premium, I would say you have two options - Premium Account or Family Organization. If you have a Free 2-person Organization Account - a reasonable upgrade would mean an upgrade to Family Organization. Or am I missing something?

I have a Free 2-person Organization Account but can only upgrade to a Premium Account. Why?

**Comment by needs-coffee** [comment]
This is the GitHub repo for editing the help pages only - not for user support.
Support can be found here - https://community.bitwarden.com/
Feature requests should be submitted here - https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
--
Regards to your questions about pricing and options:
https://bitwarden.com/help/article/about-bitwarden-plans/
https://bitwarden.com/help/article/what-plan-is-right-for-me/
https://bitwarden.com/help/article/upgrade-from-individual-to-org/

there is contact info on each of these pages.

**Comment by tgreer-bw** [comment]
To upgrade an existing 2-person org to a family org, you'll want to reach out to our CS team here: https://bitwarden.com/contact
