### ISSUE TITLE
Add shortcut to open in browser

### ISSUE THREAD

**Issue by IvanDerlichBitex** [bitwarden/help#769]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by needs-coffee** [comment]
This is the GitHub repo for editing the help pages only - not for user support.
Bugs/improvements to the mobile app should be submitted here - https://github.com/bitwarden/mobile/issues
Feature requests should be submitted here - https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
Support can be found here - https://community.bitwarden.com/

What would help is if you provided further information regarding what you are looking to have a shortcut and what you expect to open in the browser but please post this in the above locations.
