### ISSUE TITLE
Inline CSV Wrong

### ISSUE THREAD

**Issue by qqii** [bitwarden/help#783]
The inline CSV after "For Example:" at https://bitwarden.com/help/article/condition-bitwarden-import/#for-your-personal-vault seems to be incorrect. The sample csv does not seem to have the same errors. I have not verified any other files on this page

![image](https://user-images.githubusercontent.com/6891353/139286795-1d2a98eb-f559-43cb-8764-675ebe31f886.png)

**Comment by fschillingeriv** [comment]
That's a great catch @qqii! It looks like the format shifted a bit when we added `reprompt`, I'll get that updated ASAP. Thanks again for finding it!
