### ISSUE TITLE
Biometrics help page should mention that Windows Hello doesn't work with Bitwarden from the Microsoft Store

### ISSUE THREAD

**Issue by TranquilMarmot** [bitwarden/help#788]
https://bitwarden.com/help/article/biometrics/

I spent a while trying to figure out how to turn on biometrics on the Bitwarden desktop app. Turns out that it was because I downloaded it from the Windows Store and Windows Hello support only exists if Bitwarden is insalled directly from the site.

This should be mentioned on the page! Would have saved me a bit of time.

**Comment by fschillingeriv** [comment]
Hey @TranquilMarmot, unless you're trying to activate the Browser Extension integration, Windows Hello _should_ work with the Windows Store Desktop App.

I'm sorry this gave you trouble, in the future please don't hesitate to reach out to our support team at https://bitwarden.com/contact for similar issues!
