### ISSUE TITLE
Fingerprint phrase

### ISSUE THREAD

**Issue by mjvandermeulen** [bitwarden/help#790]
https://bitwarden.com/help/article/fingerprint-phrase/

### existing:
- What is my fingerprint phrase used for?
- Where can I find my fingerprint phrase?
### I suggest adding:
- Do I need to write down the fingerprint phrase?

I'm new to Bitwarden and a little cognitively overloaded on what to do/ what not to do. I was just rescued by my having written down the 32 cahracter code. I may be a little paranoid. Knowing what codes I can always look up and what codes need to be remembered is SUPER helpful.

**Comment by fschillingeriv** [comment]
This is a great question @mjvandermeulen, and a great suggested addition to the article. 

Long story short; your fingerprint phrase isn't currently used in any "log in" or "unlock" workflow, so you won't ever find yourself in a situation where you aren't able to get into your vault to look it up.

Your [Two-step Login Recovery Code](https://bitwarden.com/help/article/two-step-recovery-code/), as you've experienced first-hand, is another story.

**Comment by mjvandermeulen** [comment]
Thank you @fschillingeriv.  My feedback being taken this seriously is a joy.
