### ISSUE TITLE
Fingerprint Phrase Different on Devices

### ISSUE THREAD

**Issue by krisludington** [bitwarden/help#792]
The discussion page on the Fingerprint Phrase says nothing about what to do if the Fingerprint Phrase is different on different devices logged into the same account, which is the case for my account. Is that normal or is there a problem?  If the latter, what do I do?  Please complete the documentation.

**Comment by fschillingeriv** [comment]
Hey @krisludington, there shouldn't be any cases where your fingerprint phrase is different device-to-device. Would you mind double-checking that they're logged into the same account?

**Comment by krisludington** [comment]
Wrong. There is one case, and I figured out what it is. Both devices were logged in with the same email address and same password, but you didn’t consider the case, which is documented on your website, where access to the Authenticator app is lost and you are permanently locked out of your Vault. This is exactly what happened to me. I was trying to login to Bitwarden on a new MS Edge profile, with two-step login activated, but the Bitwarden entry in the Google Authenticator app on my iPhone had disappeared for no apparent reason after a year of use. So, according to the instructions on your website, I checked the Bitwarden app on my phone and found that it was still logged in and used it to export my information. I then went back to Edge and created a new account with the same credentials and then imported my information from the export file, again, according to the website instructions. However, the iPhone Bitwarden app was TOO STUPID to check that the account underlying the credentials had changed. As soon as I logged out and back in, the fingerprint phrase on the iPhone app changed and was the same as the one on my desktop device.  The problem here is that the “account” is not unique to the username (email address) used to login. You should have thought of that and asked me if I had recently been locked out of my Vault. Better yet, you should have consulted your system and seen that my devices were using different accounts, since I have no way to determine what account I am using other than the username, which was the same.
________________________________

**Comment by tgreer-bw** [comment]
Hi @krisludington - thanks for the clarification.

The account data is saved locally after you log in, thus why you saw the old fingerprint phrase. 

When you deleted your original account, it was permanently deleted from the Bitwarden servers which would prevent us from being able to see anything regarding it.

For future support requests, the best place to submit a ticket is https://bitwarden.com/contact

**Comment by krisludington** [comment]
> Hi @krisludington - thanks for the clarification.
> 
> The account data is saved locally after you log in, thus why you saw the old fingerprint phrase.
> 
> When you deleted your original account, it was permanently deleted from the Bitwarden servers which would prevent us from being able to see anything regarding it.
> 
> For future support requests, the best place to submit a ticket is https://bitwarden.com/contact

Your app sent me here to report the problem.
