### ISSUE TITLE
Vault Timeout - Browser Extension

### ISSUE THREAD

**Issue by traumadoc2b** [bitwarden/help#793]
The help article states that: 

> If you close your browser, you will be logged out of both your Web Vault and Browser Extension.

This does not seem to be entirely true.  If you are on a Chromebook, you can close the browser windows, but it appears that when you open Chrome again, I am still logged in to the Bitwarden extension, despite having the settings 'Vault Timeout - On Browser Restart'.  

I suspect this is secondary to ChromeOS and perhaps the extension cannot differentiate from the Chrome app window being open/closed and being logged in to the device.  Even when I lock the Chromebook and enter my Google password, reopen Chrome, it is still logged in to the Bitwarden Extension.

The only way I seem to be able to get the extension to timeout and 'see' that the browser has been 'closed' is to actually Sign-Out from my Google account on the Chromebook device.

If there is a way to make the 'close browser' option work inside of ChromeOS without signing out of the device, that would be awesome.

https://bitwarden.com/help/article/vault-timeout/

**Comment by traumadoc2b** [comment]
I did just notice that the behavior from the 'Vault Timeout - System Lock' option does seem to work when locking (but not necessarily signing out) of your account on the Chromebook.

Would be nice to see the help article differentiate nuances between different browsers/OS when the exist.

**Comment by fschillingeriv** [comment]
I'm sorry @traumadoc2b, this was a mis-phrasing on my part. It should say something more like "If you quit your browser," (CTRL/CMD + Q), meaning a full _exit_ rather than closing the browser _window_.

I'll update that doc to be clearer, but in the meantime would you mind confirming that this works on ChromeOS?

**Comment by traumadoc2b** [comment]
Unfortunately, doesn't work.  I tried CTRL Q and nothing happens.  There is no CMD key on my Chromebook.  I did also try the Google search (magnifying glass key) together with Q, but no luck.

It seems there is a 'task manager' equivalent in ChromeOS that you can get to with the Google search key + ESC.  When I do this, the Chrome browser is at the top of the list of processes, however the 'End Process' button is grayed out (but available for some other processes).

I suspect that the way ChromeOS works, there is no way to logout of Chrome or close the 'browser' session without logging out of your session on the Chromebook completely.

-Dustin

________________________________

**Comment by fschillingeriv** [comment]
That's a bummer, but thanks for giving it a try. I'm going to tag in @tangowithfoxtrot, who's got more Chromebook experience than me - hopefully he can weigh in on whether there's anything we can do to get that behavior acting right.

**Comment by traumadoc2b** [comment]
+1 for adding something about ChromeOS to the help article, perhaps with YMMV commentIt seems to me that you don't have to 'restart' the device. I changed my setting in Bitwarden to timeout On System Lock and it seems to do so when my Chromebook either goes to sleep, I 'lock' the device, sign out of the device, or power the device down.  Basically anything that takes you back to the Chromebook login screen, requiring you to renter your Google password. On Nov 2, 2021 11:25, tangowithfoxtrot ***@***.***> wrote:
It seems that, on Chrome OS, you can't truly close Google Chrome, which means that the "On Browser Restart" option won't actually function any differently than the "On System Restart" option.
Perhaps we could add a caveat in the docs to clarify this:

Please note that on Chromebooks, there is no way to fully close or restart the browser. Therefor, the "On Browser Restart" option will only lock the extension when you restart your device.
