### ISSUE TITLE
Sync with Active Directory or LDAP

### ISSUE THREAD

**Issue by dsekelj** [bitwarden/help#808]
https://bitwarden.com/help/article/ldap-directory/

Incorrect syntax for LDAP filter. 
The first "sample" uses a dash (-) instead of a equal to sign (=). 
(&(objectClass-user)(cn=*Marketing*)) should be
(&(objectClass=user)(cn=*Marketing*))

**Comment by fschillingeriv** [comment]
Good catch! Resolved by #815.
