### ISSUE TITLE
Add note about self-hosted environments for Bitwarden Icons

### ISSUE THREAD

**Issue by haneef95** [bitwarden/help#813]
Hi,

Could a note be added for self-hosted environments please? As this article isn't accurate for self-hosted environments, since, self-hosted environments have their own `icons` container.

https://bitwarden.com/help/article/website-icons/

Thanks,

**Comment by fschillingeriv** [comment]
Good suggestion @haneef95! Resolved by #815

**Comment by haneef95** [comment]
Thanks

**Comment by haneef95** [comment]
This note may not be entirely accurate to be honest.
> If you’re self-hosting Bitwarden, icons are not cached to a CDN. All requests will always hit your icon container directly.

I would suggest:
> If you’re self-hosting Bitwarden, by default requests are sent to `https://your.domain.com/icons`. The exact URL, CDN, caching and privacy configurations are managed by your infrastructure administrator(s).

Additionally, if there could be a note for infrastructure admins on how to avoid `cf-cache-status: MISS` for Cloudflare, that would be great! As I'm sure a lot of other installations also use Cloudflare for Security and CDN reasons.

Thanks,
