### ISSUE TITLE
Bitwarden Help Center - Keyboard Shortcuts - Microsoft Edge conflict with Bitwarden

### ISSUE THREAD

**Issue by AndyDaSilva52** [bitwarden/help#817]
Bitwarden Help Center Link: [Keyboard Shortcuts | Bitwarden Help & Support](https://bitwarden.com/help/article/keyboard-shortcuts/)

There are two shortcuts that are used by Edge as default:

| Press this Key | To do this |
|----------------|------------|
| CTRL + SHIFT + L | Paste and search or Paste and go (if it's a URL)|
|CTRL + SHIFT + Y | Open Collections|

[Keyboard shortcuts in Microsoft Edge](https://support.microsoft.com/en-us/microsoft-edge/keyboard-shortcuts-in-microsoft-edge-50d3edab-30d9-c7e4-21ce-37fe2713cfad)

So, this make necessary to make an adjustment at Edge configuration and try to suppress the default behaviour of Edge.

`edge://extensions/shortcuts` [Edge Extension Shortcuts](edge://extensions/shortcuts)

**Comment by fschillingeriv** [comment]
Thanks @AndyDaSilva52! There's already a bit in there about shortcut conflicts, but I'll make some edits to callout Edge in particular. Thanks!
