### ISSUE TITLE
Unlock with PIN

### ISSUE THREAD

**Issue by rupertpaulson** [bitwarden/help#829]
I have a question regarding the following note on the "Unlock with PIN" help page.
[https://bitwarden.com/help/article/unlock-with-pin/](https://bitwarden.com/help/article/unlock-with-pin/)

> **Note**
When using the **Lock with master password on restart** PIN option, the Bitwarden application may not fully purge sensitive data from application memory when entering a locked state. If you are concerned about your device’s local memory being compromised, you should not use this option.

Maybe I'm misunderstanding the note, but I assume that the note should correctly inform the reader that "When unchecking the **Lock with master password on restart** option, the Bitwarden application may not fully purge sensitive data from application memory when entering a locked state. If you are concerned about your device’s local memory being compromised, you should not uncheck this option", as a user can still use the PIN after a restart if the option is unchecked, hence not all data has been purged from memory.

At least that's how I understand:

> Tip
The pre-checked option **Lock with master password on restart** will require you to enter your Master Password instead of the PIN when the app restarts. If you want the ability to unlock with a PIN when the app restarts, uncheck this option.

**Comment by fschillingeriv** [comment]
Hey @rupertpaulson, you're absolutely correct - since the option is "on by default", the warning is referencing situations where a user un-checks or turns off the option. 

Thanks for pointing that out! I'll get it updated soon.

**Comment by fschillingeriv** [comment]
Excellent points!

"...PIN option" is referencing the fact that this option only applies to Unlock with PIN. I agree that word might mislead more than help. 

I'm going to go with "you should keep the **Lock with master password on restart** option turned on" just to be extra explicit here.

Commit inbound.
