### ISSUE TITLE
Make the help section available in .pdf therefore available to read offline

### ISSUE THREAD

**Issue by woodboy12** [bitwarden/help#839]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).
Make the help section available in .pdf therefore available to read offline

**Comment by fschillingeriv** [comment]
Hey @woodboy12, you can clone the git repository to get an offline-readable version! 

As far as PDFs go, that's a bit tough considering how interconnected the Help Center is, but nevertheless it's an interesting idea! I'll bring it to the team :)
