### ISSUE TITLE
For mobile consider moving the search button to the bottom where it's easier to press or have it be a popup bubble at the bottom.

### ISSUE THREAD

**Issue by cire4** [bitwarden/help#842]
Suggest an edit, addition, or any other comment specific to the Bitwarden Help Center (i.e. Documentation). If this suggestion is for a specific article, please supply the article title or link.

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by fschillingeriv** [comment]
Hey @cire4; are you referring to the search function within the Bitwarden Mobile App, or the Help Center when using a mobile browser?

**Comment by cire4** [comment]
The search function within the bitwarden mobile app. With phone screens
being so large now, it's difficult to reach the top right hand corner of
the screen while holding the phone in one hand. It would be nice if the
search function was similar to the edit button where it's a bubble at the
bottom right hand of the screen.

**Comment by needs-coffee** [comment]
Hi @cire4 
This is the GitHub repo for editing the help pages only for https://bitwarden.com/help/ - not for user support or feature request for the Bitwarden applications.

Bugs/improvements to the mobile app should be submitted here - https://github.com/bitwarden/mobile/issues
Feature requests should be submitted here - https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
Support can be found here - https://community.bitwarden.com/

Best place for this would be to post it on the community page above at it will get more traffic, it will not get much attention on this repo.

**Comment by fschillingeriv** [comment]
Thanks for hopping in @needs-coffee! Closing this issue.
