### ISSUE TITLE
Disable the web extension asking to save when not logged

### ISSUE THREAD

**Issue by Gerard-PC83** [bitwarden/help#844]
I think The web extension should not ask to save the password when i'm not logged in.
Or there should be an option for that in the settings.

Don't you think ?

**Comment by fschillingeriv** [comment]
Hey @Gerard-PC83, thanks for getting in touch! This repository is exclusively for the Help Center; we recommend joining (or starting!) a discussion on community.bitwarden.com to talk about changes you'd like to see to the product itself.

**Comment by longzheng** [comment]
This is a bug with the browser extension also reported https://github.com/bitwarden/browser/issues/2242

Apparently the code has been fixed https://github.com/bitwarden/browser/pull/2225 but not published yet.
