### ISSUE TITLE
Italian language incorrect translation

### ISSUE THREAD

**Issue by QwertyITA** [bitwarden/help#846]
When you copy a password you get a message saying "Password copiato", but it should be "Password copiata"

**Comment by djsmith85** [comment]
Hi @QwertyITA and thank you for bringing this up.

The translations are done by our awesome community using [Crowdin](https://crowdin.com/profile/kspearrin).

If you'd like to contribute please sign for up for Crowdin and go to the project (web, desktop, browser, mobile) where you encountered the false translation. There you can add or upvote an existing translation.

Closing this issue now.
