### ISSUE TITLE
Discurage Yubikey OTP

### ISSUE THREAD

**Issue by Ofenhed** [bitwarden/help#853]
In the [Yubikey MFA page](https://bitwarden.com/help/article/setup-two-step-login-yubikey/), a disclaimer should discourage the use of Yubikey OTP. This mode of authentication provides no protection against phishing attacks, and if the Yubikey is added on an untrusted machine the entire MFA state can be eavesdropped without the user having a chance to notice. The disclaimer should encourage users to use [WebAuthn](https://bitwarden.com/help/article/setup-two-step-login-fido/) with their Yubikeys instead.

**Comment by fschillingeriv** [comment]
Yeah, that's a really good suggestion @Ofenhed. From my research, it seems like keys prior to the 5 series don't support WebAuthn, but please let me know if you know that to be incorrect.

Otherwise, refer to the referenced commit to see what we're planning to add.

**Comment by Ofenhed** [comment]
I haven't looked at the 4 series for a very long time, but I believe you are correct.

Looks good to me 😊

**Comment by fschillingeriv** [comment]
This issue has been implemented, thanks @Ofenhed!
