### ISSUE TITLE
Shared ids lacking in exports

### ISSUE THREAD

**Issue by mukrome** [bitwarden/help#854]
Current exports of an entire vault don’t include ids/passwords that are shared with somebody else.

Shouldn’t they be included ?

**Comment by fschillingeriv** [comment]
Hey, @mukrome , there are actually two separate export procedures to tackle two cases:

1. [Export a Personal Vault](https://bitwarden.com/help/article/export-your-data/#export-a-personal-vault), which exports all Vault items owned by the exporting user.
2. [Export an Organization Vault](https://bitwarden.com/help/article/export-your-data/#export-an-organization-vault), which exports all Vault items owned by an Organization (a.k.a shared between users).

If you following the 2nd procedure, you'll get an export of the shared items you're looking for!
