### ISSUE TITLE
Finding App's URI Easily

### ISSUE THREAD

**Issue by Hoosierotter** [bitwarden/help#858]
When working from your android device you can find a specific app's URI via the Play Store. 

-Pull up said app on Play Store
-Click to share
-The app id will be contained within the hyperlink thats offered to copy/share. 

(Getting the the play store to render in desktop mode on an android browser can be somewhat cumbersome & flat out irksome as of late. This may save you a few pulled hairs.) 

https://bitwarden.com/help/article/uri-match-detection/#default-match-detection

For things related to Bitwarden apps:
- FEATURE REQUESTS: https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.
- BUG REPORTS: Create an Issue in the appropriate repository (e.g. bitwarden/mobile, bitwarden/desktop).

**Comment by fschillingeriv** [comment]
@Hoosierotter, fantastic suggestion! I've replaced the existing web browser tip with yours on https://bitwarden.com/help/uri-match-detection/ and https://bitwarden.com/help/blacklisting-uris/. Build should go through in just a few minutes, thanks for contributing!
