### ISSUE TITLE
Add Bank Accounts Field Please

### ISSUE THREAD

**Issue by BrunoSGR** [bitwarden/help#859]
Please like for a credit card add an option to enter bank accounts (With for example fields like routing number, swift code, etc)
Also it'd be cool if other features were added like passport, wifi, addresses

**Comment by needs-coffee** [comment]
Hi @BrunoSGR 
This is the GitHub repo for editing the help pages only for https://bitwarden.com/help/ - not for user support or feature request for the Bitwarden applications.

Feature requests should be submitted here - https://community.bitwarden.com/
https://community.bitwarden.com/t/about-the-feature-requests-category/12/2.

**Comment by eliykat** [comment]
We also have existing feature requests on the forums for this:
* https://community.bitwarden.com/t/building-my-own-pre-defined-item-types-templates/1959
* https://community.bitwarden.com/t/add-more-pre-defined-item-types/228

Please [sign up on our forums](https://community.bitwarden.com/signup) and you can vote for it and contribute to any discussions about it.

This issue will now be closed. Thanks!
