### ISSUE TITLE
Some website logins do not trigger autosave 

### ISSUE THREAD

**Issue by getreadyforme** [bitwarden/help#9]
Hello,

I'm not sure if this is the proper place to post this.  First off, thank you for this great alternative to LP.  BW doesn't seem to slow down page loading in Firefox the way LP does.  

The autosave feature is essential because it saves a lot of time.  While it triggers on most websites, it doesn't trigger on a few.  Would it be useful to point these out to the developers?  If yes, what is the best way to do this?
e.g. https://store.steampowered.com/login/

Thank you.

**Comment by kspearrin** [comment]
@getreadyforme You can report these in the browser extension repository issue tracker here: https://github.com/bitwarden/browser/issues
